version: '3.1'
services:
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8201:8025'
    redis:
        image: 'redis:alpine'
    mysql:
        image: 'mysql:8.0'
        restart: always
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=mysqlgb
        ports:
            - '8202:3306'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: gb-laravel
    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8200:80'
        depends_on:
            -   php-fpm
        container_name: gb-laravel_nging
    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php.ini:/etc/php/8.2/fpm/conf.d/php.ini'
        depends_on:
            - mysql
        container_name: gb-laravel_app
